CCDNUser\ProfileBundle\Entity\Profile:
    type: entity
    table: cc_user_profile
    repositoryClass: CCDNUser\ProfileBundle\Repository\ProfileRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        birthDate:
            type: date
            nullable: true
        realName:
            type: string
            nullable: true
        locationCountry:
            type: string
            nullable: true
        locationCity:
            type: string
            nullable: true
        company:
            type: string
            nullable: true
        position:
            type: string
            nullable: true
        bio:
            type: text
            nullable: true
        signature:
            type: text
            nullable: true
        avatarRemote:
            type: boolean
            column: avatar_is_remote
            nullable: false
        avatar:
            type: string
            nullable: true
        website:
            type: string
            nullable: true
        blogUrl:
            type: string
            nullable: true
        blogFeedUrl:
            type: string
            nullable: true
        aimPublic:
            type: boolean
            column: aim_is_public
            nullable: false
        aim:
            type: string
            nullable: true
        msnPublic:
            type: boolean
            column: msn_is_public
            nullable: false
        msn:
            type: string
            nullable: true
        icqPublic:
            type: boolean
            column: icq_is_public
            nullable: false
        icq:
            type: string
            nullable: true
        yahooPublic:
            type: boolean
            column: yahoo_is_public
            nullable: false
        yahoo:
            type: string
            nullable: true
    oneToOne:
        user:
            targetEntity: Symfony\Component\Security\Core\User\UserInterface
            cascade: ["persist"]
            nullable: true
            joinColumn:
                name: fk_user_id
                referencedColumnName: id
                onDelete: SET NULL
