
CCDNUserProfileBundle-User-Member:
    resource: "@CCDNUserProfileBundle/Resources/config/routing/user-member.yml"
    prefix: /{_locale}/members

CCDNUserProfileBundle-User-Profile:
    resource: "@CCDNUserProfileBundle/Resources/config/routing/user-profile.yml"
    prefix: /{_locale}/profile
