parameters:

    ccdn_user_profile.repository.profile.class:             CCDNUser\ProfileBundle\Repository\ProfileRepository

    ccdn_user_profile.gateway.profile.class:                CCDNUser\ProfileBundle\Gateway\ProfileGateway
    ccdn_user_profile.manager.profile.class:                CCDNUser\ProfileBundle\Manager\ProfileManager

    ccdn_user_profile.form.type.avatar.class:               CCDNUser\ProfileBundle\Form\Type\AvatarFormType
    ccdn_user_profile.form.type.bio.class:                  CCDNUser\ProfileBundle\Form\Type\BioFormType
    ccdn_user_profile.form.type.contact.class:              CCDNUser\ProfileBundle\Form\Type\ContactFormType
    ccdn_user_profile.form.type.personal.class:             CCDNUser\ProfileBundle\Form\Type\PersonalFormType
    ccdn_user_profile.form.type.signature.class:            CCDNUser\ProfileBundle\Form\Type\SignatureFormType
                                                            
    ccdn_user_profile.form.handler.avatar.class:            CCDNUser\ProfileBundle\Form\Handler\UpdateAvatarFormHandler
    ccdn_user_profile.form.handler.bio.class:               CCDNUser\ProfileBundle\Form\Handler\UpdateBioFormHandler
    ccdn_user_profile.form.handler.contact.class:           CCDNUser\ProfileBundle\Form\Handler\UpdateContactFormHandler
    ccdn_user_profile.form.handler.personal.class:          CCDNUser\ProfileBundle\Form\Handler\UpdatePersonalFormHandler
    ccdn_user_profile.form.handler.signature.class:         CCDNUser\ProfileBundle\Form\Handler\UpdateSignatureFormHandler

    ccdn_user_profile.component.dashboard.integrator.class: CCDNUser\ProfileBundle\Component\Dashboard\DashboardIntegrator

services:

    #
    # Repositories.
    #
    ccdn_user_profile.repository.profile:
        class: %ccdn_user_profile.repository.profile.class%
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - 'CCDNUser\ProfileBundle\Entity\Profile'

    #
    # Gateways.
    #
    ccdn_user_profile.gateway.profile:
        class: %ccdn_user_profile.gateway.profile.class%
        arguments:
            - @doctrine

    #
    # Managers.
    #
    ccdn_user_profile.manager.profile:
        class:  %ccdn_user_profile.manager.profile.class%
        arguments: 
            - @doctrine
            - @security.context
            - @ccdn_user_profile.gateway.profile
            - @ccdn_component_common.component.provider.profile

    #
    # Profile Forms.
    #
    ccdn_user_profile.form.type.avatar:
        class:  %ccdn_user_profile.form.type.avatar.class%
        arguments:
            - @doctrine
    ccdn_user_profile.form.handler.avatar:
        class:  %ccdn_user_profile.form.handler.avatar.class%
        arguments:
            - @form.factory
            - @ccdn_user_profile.form.type.avatar
            - @ccdn_user_profile.manager.profile

    ccdn_user_profile.form.type.bio:
        class:  %ccdn_user_profile.form.type.bio.class%
        arguments:
            - @doctrine
    ccdn_user_profile.form.handler.bio:
        class:  %ccdn_user_profile.form.handler.bio.class%
        arguments:
            - @form.factory
            - @ccdn_user_profile.form.type.bio
            - @ccdn_user_profile.manager.profile

    ccdn_user_profile.form.type.contact:
        class:  %ccdn_user_profile.form.type.contact.class%
        arguments:
            - @doctrine
    ccdn_user_profile.form.handler.contact:
        class:  %ccdn_user_profile.form.handler.contact.class%
        arguments: 
            - @form.factory
            - @ccdn_user_profile.form.type.contact
            - @ccdn_user_profile.manager.profile

    ccdn_user_profile.form.type.personal:
        class:  %ccdn_user_profile.form.type.personal.class%
        arguments: 
            - @doctrine
    ccdn_user_profile.form.handler.personal:
        class:  %ccdn_user_profile.form.handler.personal.class%
        arguments:
            - @form.factory
            - @ccdn_user_profile.form.type.personal
            - @ccdn_user_profile.manager.profile

    ccdn_user_profile.form.type.signature:
        class:  %ccdn_user_profile.form.type.signature.class%
        arguments:
            - @doctrine
    ccdn_user_profile.form.handler.signature:
        class:  %ccdn_user_profile.form.handler.signature.class%
        arguments:
            - @form.factory
            - @ccdn_user_profile.form.type.signature
            - @ccdn_user_profile.manager.profile

    #
    # Dashboard Integrator.
    #
    ccdn_user_profile.component.dashboard.integrator:
        class: %ccdn_user_profile.component.dashboard.integrator.class%
        arguments: [@service_container]
        tags:
            - { name: ccdn_component_dashboard.integrator }
    