parameters:

    ccdn_user_profile.repository.profile.class:             CCDNUser\ProfileBundle\Repository\ProfileRepository

    ccdn_user_profile.gateway.profile.class:                CCDNUser\ProfileBundle\Gateway\ProfileGateway
    ccdn_user_profile.manager.profile.class:                CCDNUser\ProfileBundle\Manager\ProfileManager

    ccdn_user_profile.form.type.profile_avatar.class:       CCDNUser\ProfileBundle\Form\Type\ProfileAvatarType
    ccdn_user_profile.form.type.profile_bio.class:          CCDNUser\ProfileBundle\Form\Type\ProfileBioType
    ccdn_user_profile.form.type.profile_contact.class:      CCDNUser\ProfileBundle\Form\Type\ProfileContactType
    ccdn_user_profile.form.type.profile_personal.class:     CCDNUser\ProfileBundle\Form\Type\ProfilePersonalType
    ccdn_user_profile.form.type.profile_signature.class:    CCDNUser\ProfileBundle\Form\Type\ProfileSignatureType

    ccdn_user_profile.form.handler.profile_avatar.class:    CCDNUser\ProfileBundle\Form\Handler\ProfileAvatarFormHandler
    ccdn_user_profile.form.handler.profile_bio.class:       CCDNUser\ProfileBundle\Form\Handler\ProfileBioFormHandler
    ccdn_user_profile.form.handler.profile_contact.class:   CCDNUser\ProfileBundle\Form\Handler\ProfileContactFormHandler
    ccdn_user_profile.form.handler.profile_personal.class:  CCDNUser\ProfileBundle\Form\Handler\ProfilePersonalFormHandler
    ccdn_user_profile.form.handler.profile_signature.class: CCDNUser\ProfileBundle\Form\Handler\ProfileSignatureFormHandler

    ccdn_user_profile.component.dashboard.integrator.class: CCDNUser\ProfileBundle\Component\Dashboard\DashboardIntegrator

services:

    #
    # Repositories.
    #
    ccdn_user_profile.repository.profile:
        class: %ccdn_user_profile.repository.profile.class%
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - 'CCDNUser\ProfileBundle\Entity\Profile'

    #
    # Gateways.
    #
    ccdn_user_profile.gateway.profile:
        class: %ccdn_user_profile.gateway.profile.class%
        arguments:
            - @doctrine

    #
    # Managers.
    #
    ccdn_user_profile.manager.profile:
        class:  %ccdn_user_profile.manager.profile.class%
        arguments: 
            - @doctrine
            - @security.context
            - @ccdn_user_profile.gateway.profile
            - @ccdn_component_common.component.provider.profile

    #
    # Profile Forms.
    #
    ccdn_user_profile.form.type.profile_avatar:
        class:  %ccdn_user_profile.form.type.profile_avatar.class%
        arguments:  [@doctrine]
    ccdn_user_profile.form.handler.profile_avatar:
        class:  %ccdn_user_profile.form.handler.profile_avatar.class%
        arguments:  [@form.factory, @service_container, @ccdn_user_profile.manager.profile]

    ccdn_user_profile.form.type.profile_bio:
        class:  %ccdn_user_profile.form.type.profile_bio.class%
        arguments:  [@doctrine]
    ccdn_user_profile.form.handler.profile_bio:
        class:  %ccdn_user_profile.form.handler.profile_bio.class%
        arguments:  [@form.factory, @service_container, @ccdn_user_profile.manager.profile]

    ccdn_user_profile.form.type.profile_contact:
        class:  %ccdn_user_profile.form.type.profile_contact.class%
        arguments:  [@doctrine]
    ccdn_user_profile.form.handler.profile_contact:
        class:  %ccdn_user_profile.form.handler.profile_contact.class%
        arguments:  [@form.factory, @service_container, @ccdn_user_profile.manager.profile]

    ccdn_user_profile.form.type.profile_personal:
        class:  %ccdn_user_profile.form.type.profile_personal.class%
        arguments:  [@doctrine]
    ccdn_user_profile.form.handler.profile_personal:
        class:  %ccdn_user_profile.form.handler.profile_personal.class%
        arguments:  [@form.factory, @service_container, @ccdn_user_profile.manager.profile]

    ccdn_user_profile.form.type.profile_signature:
        class:  %ccdn_user_profile.form.type.profile_signature.class%
        arguments:  [@doctrine]
    ccdn_user_profile.form.handler.profile_signature:
        class:  %ccdn_user_profile.form.handler.profile_signature.class%
        arguments:  [@form.factory, @service_container, @ccdn_user_profile.manager.profile]

    #
    # Dashboard Integrator.
    #
    ccdn_user_profile.component.dashboard.integrator:
        class: %ccdn_user_profile.component.dashboard.integrator.class%
        arguments: [@service_container]
        tags:
            - { name: ccdn_component_dashboard.integrator }
    