parameters:

    # Service Parameters defined in app/config

services:

    #
    # Repositories.
    #
    ccdn_user_profile.repository.profile:
        class: %ccdn_user_profile.repository.profile.class%
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - %ccdn_user_profile.entity.profile.class%

    #
    # Gateways.
    #
    ccdn_user_profile.gateway.profile:
        class: %ccdn_user_profile.gateway.profile.class%
        arguments:
            - @doctrine
            - %ccdn_user_profile.entity.profile.class%

    #
    # Managers.
    #
    ccdn_user_profile.manager.profile:
        class: %ccdn_user_profile.manager.profile.class%
        arguments:
            - @doctrine
            - @security.context
            - @ccdn_user_profile.gateway.profile
            - @ccdn_component_common.component.provider.profile

    #
    # Profile Types Forms.
    #
    ccdn_user_profile.form.type.avatar:
        class: %ccdn_user_profile.form.type.avatar.class%
        arguments:
            - %ccdn_user_profile.entity.profile.class%

    ccdn_user_profile.form.type.personal:
        class: %ccdn_user_profile.form.type.personal.class%
        arguments:
            - %ccdn_user_profile.entity.profile.class%

    ccdn_user_profile.form.type.contact:
        class: %ccdn_user_profile.form.type.contact.class%
        arguments:
            - %ccdn_user_profile.entity.profile.class%

    ccdn_user_profile.form.type.bio:
        class: %ccdn_user_profile.form.type.bio.class%
        arguments:
            - %ccdn_user_profile.entity.profile.class%

    ccdn_user_profile.form.type.signature:
        class: %ccdn_user_profile.form.type.signature.class%
        arguments:
            - %ccdn_user_profile.entity.profile.class%

    #
    # Profile Form Handlers.
    #
    ccdn_user_profile.form.handler.avatar:
        class: %ccdn_user_profile.form.handler.avatar.class%
        arguments:
            - @form.factory
            - @ccdn_user_profile.form.type.avatar
            - @ccdn_user_profile.manager.profile

    ccdn_user_profile.form.handler.personal:
        class: %ccdn_user_profile.form.handler.personal.class%
        arguments:
            - @form.factory
            - @ccdn_user_profile.form.type.personal
            - @ccdn_user_profile.manager.profile

    ccdn_user_profile.form.handler.contact:
        class: %ccdn_user_profile.form.handler.contact.class%
        arguments:
            - @form.factory
            - @ccdn_user_profile.form.type.contact
            - @ccdn_user_profile.manager.profile

    ccdn_user_profile.form.handler.bio:
        class: %ccdn_user_profile.form.handler.bio.class%
        arguments:
            - @form.factory
            - @ccdn_user_profile.form.type.bio
            - @ccdn_user_profile.manager.profile

    ccdn_user_profile.form.handler.signature:
        class:  %ccdn_user_profile.form.handler.signature.class%
        arguments:
            - @form.factory
            - @ccdn_user_profile.form.type.signature
            - @ccdn_user_profile.manager.profile

    #
    # Dashboard Integrator.
    #
    ccdn_user_profile.component.dashboard.integrator:
        class: %ccdn_user_profile.component.dashboard.integrator.class%
        tags:
            - { name: ccdn_component_dashboard.integrator }
