
#%ccdn_user_profile.entity.profile.class%:
CCDNUser\ProfileBundle\Entity\Profile:
    properties:
        avatar:
            - Type: { type: string, groups: [update_avatar] }
            - Length: { max: 255, groups: [update_avatar] }
        #    - Url: { protocols: ['http', 'https'], groups: [update_avatar] }
        #avatarRemote:
        #    - type: { type: bool, groups: [update_avatar] }

        locationCountry:
            - Type: { type: string, groups: [update_personal] }
            - Length: { max: 255, groups: [update_personal] }
        locationCity:
            - Type: { type: string, groups: [update_personal] }
            - Length: { max: 255, groups: [update_personal] }
        website:
            - Type: { type: string, groups: [update_personal] }
            - Length: { max: 255, groups: [update_personal] }

        realName:
            - Type: { type: string, groups: [update_info] }
        birthDate:
        #    - Type: { type: date, groups: [update_info] }
        company:
            - Type: { type: string, groups: [update_info] }
        position:
            - Type: { type: string, groups: [update_info] }

        bio:
            - Type: { type: string, groups: [update_bio] }
            - Length: { max: 2000, groups: [update_bio] }
        signature:
            - Type: { type: string, groups: [update_signature] }
            - Length: { max: 255, groups: [update_signature] }

        website:
            - Type: { type: string, groups: [update_contact] }
            - Length: { max: 255, groups: [update_contact] }
        #    - Url: { protocols: ['http', 'https'], groups: [update_contact] }
        blogUrl:
            - Type: { type: string, groups: [update_contact] }
            - Length: { max: 255, groups: [update_contact] }
        #    - Url: { protocols: ['http', 'https'], groups: [update_contact] }
        blogFeedUrl:
            - Type: { type: string, groups: [update_contact] }
            - Length: { max: 255, groups: [update_contact] }
        #    - Url: { protocols: ['http', 'https'], groups: [update_contact] }
        aim:
            - Type: { type: string, groups: [update_contact] }
            - Length: { max: 255, groups: [update_contact] }
        aimPublic:
            - Type: { type: bool, groups: [update_contact] }
        msn:
            - Type: { type: string, groups: [update_contact] }
            - Length: { max: 255, groups: [update_contact] }
            - Email: { groups: [update_contact] }
        msnPublic:
            - Type: { type: bool, groups: [update_contact] }
        icq:
            - Type: { type: string, groups: [update_contact] }
            - Length: { max: 255, groups: [update_contact] }
        icqPublic:
            - Type: { type: bool, groups: [update_contact] }
        yahoo:
            - Type: { type: string, groups: [update_contact] }
            - Length: { max: 255, groups: [update_contact] }
            - Email: { groups: [update_contact] }
        yahooPublic:
            - Type: { type: bool, groups: [update_contact] }
