parameters:

    # Service Parameters defined in app/config

services:

    #
    # Dashboard Integrator.
    #
    ccdn_user_profile.component.dashboard.integrator:
        class: %ccdn_user_profile.component.dashboard.integrator.class%
        arguments:
            - %ccdn_user_profile.member.list.requires_login%
        tags:
            - { name: ccdn_component_dashboard.integrator }

    #
    # Crumbs.
    #
    ccdn_user_profile.component.crumb_factory:
        class: %ccdn_user_profile.component.crumb_factory.class%
        arguments:
            - @translator
            - @router

    ccdn_user_profile.component.crumb_builder:
        class: %ccdn_user_profile.component.crumb_builder.class%
        arguments:
            - @ccdn_user_profile.component.crumb_factory

    #
    # Event Subscribers.
    #
    ccdn_user_profile.component.event_listener.flash:
        class: %ccdn_user_profile.component.event_listener.flash.class%
        arguments: [@session]
        tags:
            - { name: kernel.event_subscriber }
