parameters:

    # Service Parameters defined in app/config

services:

    #
    # Managers.
    #
    ccdn_user_profile.manager.user:
        class: %ccdn_user_profile.manager.user.class%
        arguments:
            - @event_dispatcher
            - @ccdn_user_profile.gateway.user

    ccdn_user_profile.manager.profile:
        class: %ccdn_user_profile.manager.profile.class%
        arguments:
            - @event_dispatcher
            - @ccdn_user_profile.gateway.profile
