parameters:

    # Service Parameters defined in app/config

services:

    #
    # Repositories.
    #
    ccdn_user_profile.repository.user:
        class: %ccdn_user_profile.repository.user.class%
        arguments:
            - @ccdn_user_profile.gateway.user

    ccdn_user_profile.repository.profile:
        class: %ccdn_user_profile.repository.profile.class%
        arguments:
            - @ccdn_user_profile.gateway.profile
